
image: Visual Studio 2017

configuration:
  - Debug
  - Release

before_build:
  - nuget restore

after_build:
  - nuget pack EFCacheContains/EFCacheContains.csproj -OutputDirectory Artifacts
  - appveyor PushArtifact EFCacheContains/Artifacts/*.nupkg

