
image: Visual Studio 2017

version: '1.0.{build}'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

configuration:
  - Release

before_build:
  - nuget restore

after_build:
  - nuget pack EFCacheContains/EFCacheContains.csproj -Version %appveyor_build_version% -OutputDirectory Artifacts
  - appveyor PushArtifact /Artifacts/EFCacheContains.%appveyor_build_version%.nupkg

